z0s3r77/BooKingBikeV2

- index.html
En esta pagina se muestra la navegación , tres parrafos informativos y un footer
> feat: Añadido una pagina index.html

- src/db/conexionApiMongo.py
He definido la función requestToMongoApi para que nos dé como resultado un string con los documentos de las bicis. Posteriormente esto se convertirá en un JSON. También he añadido comentarios.
> fix: Se ha encapsulado la peticion en requesToMongoApi

- src/db/conexionApiMongo.py
Dentro de la funcion se formateaba directamente el string, la idea es recibir la peticion en otro modulo y de ahí extraer el JSON
> fix: modificado conexionApiMongo

- src/db/prueba.py
Esto funciona por lo que parece.
> RESPONDIENDOPRUEBA

- src/db/prueba.py
El archivo de prueba.py se habia creado con el fin de ver como funcionaba el pull en local.
> fix: Se ha borrado el archivo de prueba.py

- docs/listadototalbicis.html
Hemos creado la pagina listadototalbicis la cual muestra todas las bicis que tendrá nuestra pagina web
> feat: Creamos la pagina listadototalbicis

- .gitignore
- JSON/bikes.json
- src/db/generadorJson.py
El nuevo modulo recoge la respuesta de conexionApiMongo.py  que es un string y la convierte, primero en un diccionario y despues lo vuelca en un archivo JSON.
> feat: Implementado el modulo generadorJson.py

- docs/listadotipobicis.html
La pagina incluye todos los tipos de bicis que tenemos disponibles en nuestra base de datos
> feat: Creamos la pagina listadotipobicis

- docs/listadomarcabicis.html
Una pagina la cual muestra un listado de las marcas de bicis que tenemos en la base de datos
> feat: añadimos listadomarcabicis.html

- docs/B1.html
He montado la plantilla que servirá para cada bicicleta. Los titulos de los htmls serán los IDs de las bicicletas.
> feat: Creado plantilla de especificaciones tecnicas

- docs/listadobicisporzona.html
Se ha añadido la pagina listadobicisporzona.html , en el cual se listarán todas las zonas disponibles.
> feat: Se ha añadido la vista por zonas

- docs/B1.html
- docs/home.html
- docs/listadobicisporzona.html
- docs/listadomarcabicis.html
- docs/listadotipobicis.html
- docs/listadototalbicis.html
Muchas paginas tenian etiquetas puestas de forma erronea y los enlaces no funcionaban
> fix: Se han corregido todos los enlaces y etiquetas semanticas

- src/db/conexionApiMongo.py
- src/db/generadorJson.py
Se han integrado una serie de try y except en conexionApiMongo, con el fin de comprobar que la conexion con Mongo Atlas es correcta. En generadorJson.py tan solo se ha modificado el nombre de una variable. Se ha añadido __init__.py
> perf: Se ha mejorado conexionApiMongo.py , generadorJson.py

- src/db/generadorJson.py
Se ha añadido la funcionalidad que si a la hora de crear el JSON no encuentra el directorio donde lo guarda, lo cree
> perf: Añadida funcionalidad en generadorJson.py

- src/db/convertirJsonALista.py
- src/db/generadorJson.py
- src/db/mainDb.py
Se ha creado el modulo mainDb.py que unifica todos los modulos del directorio DB para poder dar como resultado una variable con la lista de todos los documentos de la colección Bikes de MongoAtlas.
> Feature/main db.py

- src/db/conexionApiMongo.py
Eliminamos el filter de APImongo para que muestre todas las bicis
> fix: eliminar filtro

- src/crud/MongoAtlasConexion.py
- src/crud/main.py
Se ha añadido un fichero oculto que contiene las variables de entorno para poder ejecutar metodos que requieran datos privados de forma segura. Se ha modificado src/crud/main.py
> feat: Se ha añadido .env

- src/views/funcionesHTML.py
Añadimos la generación de carpetas automáticamente en funcionesHTML.py
> feat: Añadimos la generación de carpetas (funcionesHTML.py)

- docs/listadobicispordesarrollo.html
- src/views/funcionesHTML.py
Arreglamos el filtrado por desarrollo
> fix: Arregramos el filtrado por desarrollo

- json/prueba.json
- json/prueba2.json
- pytest.ini
- test/test_DB_MongoAtlasConexion.py
- test/test_DB_conexionApiMongo.py
- test/test_DB_convertirJsonALista.py
- test/test_DB_generadorJson.py
- test/test_DB_mainDB.py
Se ha podido añadir Markers. Esto no se podía ya que no entendía porque no me dejaba crear el fichero pytest.ini
> perf: Añadido Markers Pytest
